name: Deployment Workflow
on:
    push:
      branches:
        - main

jobs:
    pusher:
        runs-on: ubuntu-latest
        steps:
            - name: "Greeting step"
              run: echo "This is my first Workflow"

            - name: confirm the repository of Docker Hub
              uses: actions/checkout@v4

            - name: Logging into Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}


                
            - name: "Build the image for the App"
              env:
                  IMAGE_NAME: ghost
                  VERSION: latest
                  USERNAME: healerkay
              run: |
                    docker build -t $USERNAME/$IMAGE_NAME:$VERSION .
                    docker push $USERNAME/$IMAGE_NAME:$VERSION
